### ISSUE TITLE
Log Folder not populating

### ISSUE THREAD

**Issue by bjmarty** [polcak/pcf#3]
Hello,

Whenever I run the program, no data is populating in the logs.  I can see that there is traffic on my network, but the program is collecting and process none of the packets. Any suggestions on what I should look at next?

Thank you,
Bryan

**Comment by polcak** [comment]
Hello Bryan,

Please let us know how did you compile pcf (just make, or with parameters), how do you launch pcf and what is your config file.

Thank you,

Libor

**Comment by bjmarty** [comment]
Libor,

I compiled using just make.  When I launch pcf I use the command <sudo ./pcf -t 600 -p 80 eth0> from the src directory.  The only files I used for configuration are what I downloaded from your zip file.

Thanks!

-Bryan

**Comment by polcak** [comment]
Hello Bryan,

First, make sure that there actually are packets that have timestamps embedded in the TCP options. Secondly, running pcf in the verbose mode (-v) might also help you to learn if the pcf sees some packets with timestamps.

Did it help?

Libor

**Comment by bjmarty** [comment]
Libor,

I was initially trying to run PCF on a network we setup in our lab that is not connected to the internet.  I simulated traffic by logging into each host via SSH, and I saw via wireshark capture that there are TCP packets. I went to a host that was connected to the internet and ran PCF while visiting multiple websites.  The logs did populate when I did this.  I'm not sure why the logs won't populate when I try to SSH into another host.

On a related note, for the logs I had four columns.  What are the values for each column?  The last two look like timestamp for the source and destination.  For the first two coulmns I was getting all zeros.

Thank you.

-Bryan

**Comment by bjmarty** [comment]
UPDATE:  I was able to collect timestamps on hosts within my closed network that had port 80 open.  My initial attempt at simulating traffic only went to port 22 for SSH.  I'm still getting zero values for the first two columns, but columns 3 and 4 are populating.

Now that I have the logs I'm not sure where to go next in order to extract the clock skews for each host.

-Bryan

**Comment by polcak** [comment]
Hello Bryan,

with the "-p 80" option, you limit the computation to the port 80 only. If you omit this option (and also make sure that it is not configured in the config file that the pcf opens) then all traffic will be processed. The default config file contains the line "port 80", just remove it or comment it ("#port 80").

In the www/graph/_method_ you should see graphs of the timestamps that the pcf saw. You should see line segments specified by linear function f_n(x) = alpha * x + beta. When you multiply alpha by 1000, you will get the ppm difference in the time measurement between the monitoring node and the computer having the listed IP address.

If you manage to set up a web server and PHP for the www directory, you should be able to interpret the PHP files in a web browser.

The files in the log directory are usually not so much informative. I rarely use them. There is one line for every packet analysed. If I remember correctly, the first column contains the time since the start of the measurement. The third column contains the unix timestamp of the time when the packet was received (usually added by the OS kernel). Basically, the first column can be computed as the "third column - third column of the first packet". The fourth column contains the analysed time stamp inside the packet (TCP/JS/ICMP). The second column is the accumulated difference of the local time and the remote time, i.e. "((fourth column - fourth column of the first row)/1000 - 1st column) * 1000".

If you have the first two columns all zeroes, it means that you are receiving too much data sent at the same time. Try to analyse lower amount of traffic.

Does it make sense to you?

Libor

**Comment by bjmarty** [comment]
Libor,

I am not seeing anything www/graph/_method_ directories for TCP/ICMP/JS.  I ran the program using -p 22 and have collected some data.  Logs are populating for all the hosts in my network I am also getting *.gp files in my bin/graph/_method_ directories but I do not know how to utilize them.

If I go to the www/data/_method_ directory I am also being an xml file that list the host's IP, clock frequency, time it was up, and the number of packets collected.  There is a skew field here but it is blank for all the hosts.

We're making progress.  Thank you for all the help.

-Bryan

**Comment by polcak** [comment]
Hello Bryan,

the .gp files are source files for gnuplot that should create graphs. Do you have gnuplot installed?

However, depending on your usecase, you might want to work with the XMLs. The XML you are talking about the active.xml? You should see the skew value there for every IP. It is basically listed in kppm (1000 ppm). I guess, that the skews element is empty there. Do you see frequency there? Is it like 100, 250, 1000 or so or is it some random number?

IIRC, pcf should compute clock skew after 5 minutes provided that the frequency is known. I am not sure what is the relation between the running time and number of packets when the program recomputes the clock skew. Anyway, maybe try to run pcf little bit longer, lets say at least 20 minutes. It might also make sense to keep pcf running and just monitor its output files to see if the skew is computed later.

Also, you might want to capture a pcap file of about let's say 20 minutes or even more and try to run pcf with the option "-o pcapfilename". That way you will not need to wait for a long time every run.

Libor

**Comment by bjmarty** [comment]
Libor,

Collecting more data worked.  The clock skews are now populating.  I haven't installed gnuplot yet, but I'll let you know if I have any issues.  Thanks for all your help.

-Bryan

**Comment by ka1chawla** [comment]
Hello  Polcak ,

     Can u please elaborate how to install this project on my machine, (mac) . Also please guide me through these dependencies . 

Thank you

**Comment by polcak** [comment]
Hello,

I am closing this issue as it seems that bjmarty succeeded.

About the ka1chawla's question: see README, 1st paragraph "The program was developed and tested
in GNU/Linux." Other platforms may or may not work. It is up to you to figure out the dependencies. I added a similar note to the INSTALL file.

Feel free to fork the project and provide a port for MacOS.
